### PR TITLE
Changes to Make Theme WP Coding Standards Compliant

### PR DESCRIPTION
**Pull request by timnolte**
First Pass at Making Theme WP Coding Standards Compliant
- Fixes missing dependencies parameter for Google Font enquing.
- Adds an optional section to allow loading admin-specific scripts.

### CODE REVIEW

**Comment by timnolte** [comment]
@coreylafferty just a heads up that I've been ignoring this for awhile and now that I'm working on a new build project I just can't let it go any longer. Gesso is not complaint with WordPress coding standards. This will be a large PR to fix all of that. I'm not sure how far I'll take this as I'd like to ensure all changes going forward meet WP coding standards.

**Comment by timnolte** [comment]
@coreylafferty FYI, Codacy isn't actually reporting all of the coding standards issues, there are like 40 remaining issues that are reported when I run the checks locally and Codacy is only report 2.

**Comment by timnolte** [comment]
@coreylafferty so this should be all completed and ready to merge in.

**Comment by timnolte** [comment]
@coreylafferty I've removed Codacy, both the online configuration & local Docker setup from this branch/PR.

**Review by kmonahan — APPROVED** [review]

**Pull request merged**
