### PR TITLE
Base boilerplate code to register ACF powered custom blocks for Guten…

### PR DESCRIPTION
**Pull request by elvismdev**
…berg editor and render via Twig/Timber template.

### CODE REVIEW

**Comment by timnolte** [comment]
I don't know that I agree with this being in the theme files. You have to ensure that this code made it to a new theme for any rebuilds otherwise you'd lose your blocks.

**Comment by elvismdev** [comment]
@timnolte This base code is only to define theme blocks built with ACF fields which is pretty often the case for our builds. Gesso theme builds doesn't pull again code from the repo, as is a starter theme it is a one off pull only during project setup.

**Comment by timnolte** [comment]
@elvismdev but this code is included int the theme and to me ACF blocks are for content not the theme.

**Comment by elvismdev** [comment]
> @elvismdev but this code is included int the theme and to me ACF blocks are for content not the theme.

@timnolte Oh I see what you mention. And I'm noticing now that the recommended method to register and create new blocks it to have it's own plugin for it. Doing it on the theme definitely adds theme lockin and content can break if theme is changed.

**Pull request closed without merging**
